import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { Roboto, Open_Sans, Ubuntu_Mono } from "next/font/google";

import "./globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight
// Inter
// const inter = Lato({
//   subsets: ["latin"],
//   display: "swap",
// });

const openSans = Open_Sans({ weight: "500", subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body>{children}</body>
      <Analytics />
    </html>
  );
}
